#ifndef OPCODES_H
#define OPCODES_H

const int LOGIN_REQUEST = 0x01;
const int LOGIN_RESPONSE = 0x02;
const int LOGOUT_REQUEST = 0x03;
const int LOGOUT_RESPONSE = 0x04;
const int GET_ONLINE_USER_LIST_REQUEST = 0x05;
const int GET_ONLINE_USER_LIST_RESPONSE = 0x06;
const int CLIENT_COMUNICATION_REQUEST = 0x07;
const int SERVER_COMUNICATION_REQUEST = 0x08;
const int CLIENT_COMUNICATION_RESPONSE = 0x09;
const int SERVER_COMUNICATION_RESPONSE = 0x0A;
const int CLIENT_COMMUNICATION_DATA = 0x0B;


#endif // OPCODES_H
